config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/project_edit' => 'application#redirect_to_last_edit'
  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :donations, only: [:create] do
    collection do
      get :confirm
    end
  end
  resources :auto_complete_cities, only: [:index]
  resources :flexible_projects do
    member do
      get :publish
      get :push_to_online
      get :validate_publish
      get :finish
    end
  end
  resources :projects, only: [ :index, :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :destroy ]
    resources :rewards do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :fallback_create, to: 'projects/contributions#create'
      end
      member do
        get 'toggle_anonymous'
        get :second_slip
        get :no_account_refund
      end
      put :credits_checkout, on: :member
    end

    collection do
      get :fallback_create, to: 'projects#create'
    end
    get 'video', on: :collection
    member do
      get 'insights'
      put 'pay'
      put 'push_to_flex'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
      get 'validate_publish'
      get 'push_to_online'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      #get :balance
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
      post :new_password
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => redirect("/start")
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'
  get "/flex" => 'high_voltage/pages#show', id: 'flex'
  get "/projects_dashboard" => 'high_voltage/pages#show', id: 'projects_dashboard'


  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [] do
      member do
        put 'gateway_refund'
      end
    end

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/project/all_or_nothing_state_validator.rb
# -*- coding: utf-8 -*-
# This module handles with default state validation
module Project::AllOrNothingStateValidator
  extend ActiveSupport::Concern

  included do
    with_options if: ->(x) { x.mode == 'aon' } do |wg| 
      # Validation for in_analysis? only state
      wg.with_options if: :in_analysis? do |wo|
        wo.validates_presence_of :city
        wo.validates_length_of :name, maximum: Project::NAME_MAXLENGTH
      end

      # Start validations when project state
      # is included on ON_ANALYSIS_TO_END_STATE
      wg.with_options if: -> (x) { Project::ON_ANALYSIS_TO_END_STATES.include? x.state } do |wo| 
        wo.validates_presence_of :goal, :online_days, :budget
      end
    end
  end
end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    @@routes = Rails.application.routes.routes
    validate :permalink_cant_be_route, allow_nil: true
    # This code might come back in a near future
    #validate :ensure_at_least_one_reward_validation, unless: :is_flexible?


    def self.get_routes
      @@mapped_routes ||= @@routes.inject(Set.new) do |memo, item|
        memo << $1 if item.path.spec.to_s.match(/^\/([\w]+)\S/)
        memo
      end
    end

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
    
    def ensure_at_least_one_reward_validation
      errors.add(
        'rewards.size',
        I18n.t("activerecord.errors.models.project.attributes.rewards.at_least_one")
      ) if rewards.empty?
    end
  end
end

app/models/concerns/project/video_handler.rb
module Project::VideoHandler
  extend ActiveSupport::Concern
  include Shared::VideoHandler

  included do
    mount_uploader :video_thumbnail, ProjectUploader

    def download_video_thumbnail
      self.video_thumbnail = open(self.video.thumbnail_large)  if self.video_valid?
      self.save
    rescue OpenURI::HTTPError, TypeError => e
      Rails.logger.info "-----> #{e.inspect}"
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_at, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash
    end

    redirect_to admin_projects_path
  end

  def update
    resource.update_attributes(permitted_params)
    super
  end

  protected
  def permitted_params
    params.require(:project).permit(resource.attribute_names.map(&:to_sym))
  end

  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  DEFAULT_AMOUNT = 10
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: (params[:amount].presence || DEFAULT_AMOUNT).to_i)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.origin = Origin.process_hash(referral)
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  def no_account_refund
    authorize resource
  end

  def second_slip
    authorize resource
    redirect_to resource.details.ordered.first.second_slip_path
  end

  def toggle_anonymous
    authorize resource
    resource.toggle!(:anonymous)
    return render nothing: true
  end

  protected
  def load_rewards
    if @project.rewards.present?
      empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
      @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
    else
      @rewards = []
    end
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  def parent
    @project ||= Project.find params[:project_id]
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to edit_project_path(parent, anchor: 'posts')
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class InvalidProject < StandardError; end
class SuccessfulProject < StandardError; end
class ProjectsController < ApplicationController

  after_filter :verify_authorized, except: %i[show index video video_embed embed embed_panel about_mobile]
  after_filter :redirect_user_back_after_login, only: %i[index show]
  before_action :authorize_and_build_resources, only: %i[edit]

  has_scope :pg_search, :by_category_id
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  helper_method :project_comments_canonical_url, :resource, :collection

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  before_action :referral_it!

  def index
    respond_to do |format|
      format.html do
        return render_index_for_xhr_request if request.xhr?
      end
      format.atom do
        return render layout: false, locals: {projects: projects}
      end
      format.rss { redirect_to projects_path(format: :atom), :status => :moved_permanently }
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @project.rewards.build
  end

  def create
    @project = Project.new
    @project.attributes = permitted_params.merge(
      user: current_user,
      origin: Origin.process_hash(referral))
    authorize @project
    if @project.save
      redirect_to insights_project_path(@project)
    else
      render :new
    end
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource_action :send_to_analysis, :analysis_success
  end

  def publish
    authorize resource
  end

  def validate_publish
    authorize resource
    Project.transaction do
      raise InvalidProject unless resource.push_to_online
      raise SuccessfulProject
    end
  rescue InvalidProject
    flash.now[:notice] = t("projects.push_to_online_error")
    build_dependencies
    render template: 'projects/edit'
  rescue SuccessfulProject
    redirect_to publish_project_path(resource)
  end

  def push_to_online
    authorize resource
    resource_action :push_to_online, nil, true
  end

  def insights
    authorize resource, :update?
  end

  def update
    authorize resource

    #need to check this before setting new attributes
    should_validate = should_use_validate

    resource.localized.attributes = permitted_params
    #can't use localized for fee
    if permitted_params[:service_fee]
      resource.service_fee = permitted_params[:service_fee]
    end

    should_show_modal = resource.mode == 'flex' && resource.online_days_changed?


    if resource.save(validate: should_validate)
      flash[:notice] = t('project.update.success')
    else
      flash[:notice] = t('project.update.failed')
      build_dependencies
      return render :edit
    end

    if should_show_modal
      redirect_to insights_project_path(@project, show_modal: true)
    elsif params[:anchor]
      redirect_to edit_project_path(@project, anchor: params[:anchor])
    else
      redirect_to edit_project_path(@project, anchor: 'home')
    end
  end

  def show
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
    @post ||= resource.posts.where(id: params[:project_post_id].to_i).first if params[:project_post_id].present?
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  # TODO: remove when flex goes public
  def push_to_flex
    authorize resource
    resource.build_flexible_project
    resource.state = 'draft'
    resource.online_days = nil
    resource.expires_at = nil
    resource.save!
    resource.project_transitions.destroy_all
    redirect_to :back 
  end

  def embed
    resource
    render partial: 'card', layout: 'embed', locals: {embed_link: true, ref: (params[:ref] || 'ctrse_embed')}
  end

  def embed_panel
    resource
    render partial: 'project_embed'
  end

  protected
  def authorize_and_build_resources
    authorize resource
    build_dependencies
  end

  def build_dependencies
    @posts_count = resource.posts.count(:all)
    @user = resource.user
    @user.links.build
    @post =  (params[:project_post_id].present? ? resource.posts.where(id: params[:project_post_id]).first : resource.posts.build)
    @rewards = @project.rewards.rank(:row_order)
    @rewards = @project.rewards.build unless @rewards.present?

    resource.build_account unless resource.account
  end

  def resource_action action_name, success_redirect=nil, show_modal=nil
    if resource.send(action_name)
      if resource.origin.nil? && referral.present?
        resource.update_attribute(
          :origin_id, Origin.process_hash(referral).try(:id))
      end

      flash[:notice] = t("projects.#{action_name.to_s}")
      if success_redirect
        redirect_to edit_project_path(@project, anchor: success_redirect)
      else
        if show_modal
          redirect_to insights_project_path(@project, online_succcess: true)
        else
          redirect_to insights_project_path(@project)
        end
      end
    else
      flash.now[:notice] = t("projects.#{action_name.to_s}_error")
      build_dependencies
      render :edit
    end
  end

  def render_index_for_xhr_request
    render partial: 'projects/card',
      collection: projects,
      layout: false,
      locals: {ref: "explore", wrapper_class: 'w-col w-col-4 u-marginbottom-20'}
  end

  def projects
    page = params[:page] || 1
    @projects ||= apply_scopes(Project.visible.order_status).
      most_recent_first.
      includes(:project_total, :user, :category).
      page(page).per(18)
  end

  def should_use_validate
    resource.valid?
  end

  def permitted_params
    params.require(:project).permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def project_comments_canonical_url
    url = project_by_slug_url(resource.permalink, protocol: 'http', subdomain: 'www').split('/')
    url.delete_at(3) #remove language from url
    url.join('/')
  end
end

app/views/catarse_bootstrap/projects/_aon_nav_actions.html.slim
- if @project.draft?
   = link_to t('.send'), send_to_analysis_project_path(@project), class: 'btn btn-medium'
- if @project.approved?
   = link_to validate_publish_project_path(@project), class: 'btn btn-medium' do
    = t('.publish')
    | &nbsp;&nbsp;
    span.fa.fa-chevron-right

app/views/catarse_bootstrap/projects/_aon_preview_explanation.html.slim
.u-text-center
  .w-container
    .w-row
      .w-col.w-col-8.w-col-push-2
        .fontweight-semibold.fontsize-large.u-margintop-40= t('projects.dashboard_preview.aon.header_subtitle') 
        p.fontsize-base= t('projects.dashboard_preview.aon.header_text') 
        .w-row.u-marginbottom-30
          .w-col.w-col-3
          .w-col.w-col-6
            input.w-input.text-field value="#{project_by_slug_url(@project.permalink, locale: '')}" type="text"
          .w-col.w-col-3
      .w-col.w-col-2

app/views/catarse_bootstrap/projects/_dashboard_announce_expiration.html.slim
#dashboard-announce_expiration-tab
  = simple_form_for @project, html: { class: 'project-form w-form', id: 'expiration-form' } do |form|
    .w-section
      .w-container
        .w-row.u-marginbottom-60
          .w-col.w-col-1
          .w-col.w-col-10
            = @project.display_errors(:announce_expiration)
            .card-big.card.card-terciary.u-radius
              .w-row.u-marginbottom-30
                .w-col.w-col-6._w-sub-col
                  .fontsize-small.u-marginbottom-10
                    | Em quantos dias, contados a partir de agora, você quer encerrar a sua arrecadação?
                    br
                    span.fontsize-smaller.fontweight-semibold
                      |(mínimo de 2 dias e máximo 60 dias)
                .w-col.w-col-6
                  .w-row
                    .w-col.w-col-8.w-col-small-6.w-col-tiny-6
                      = form.input :online_days, as: :numeric, default: 2,
                        wrapper: :two_columns,
                        input_html: { class: 'positive medium', required: false, value: '2' },
                        validation_text: false, label: '', hint: ''
                    .w-col.w-col-4.w-col-small-6.w-col-tiny-6.text-field.postfix.no-hover.medium.prefix-permalink
                      .fontcolor-secondary.u-text-center.fontsize-base.lineheight-tightest Dias
              .fontcolor-secondary.u-text-center
                .fontsize-smaller Você poderá receber apoios até:
                .fontsize-base
                  span.expire-date=> l(2.days.from_now.to_date)
                  | as 23h59m
          .w-col.w-col-1
    .w-section
      .w-container
        .w-row
          .w-col.w-col-4
          .w-col.w-col-4
            a#show-modal.btn.btn-large.u-marginbottom-20   Confirmar

    .modal-backdrop.w-hidden
      .modal-dialog-outer
        .modal-dialog-inner.modal-dialog-small
          a.w-inline-block.modal-close.fa.fa-close.fa-lg  href="#announce_expiration"
          .modal-dialog-content
            .fontsize-large.u-text-center.u-marginbottom-30.fontweight-semibold Você confirma?
            .fontsize-large.u-text-center.u-marginbottom-30
              'Sua arrecadação irá terminar no dia 
              span.expire-date= l(2.days.from_now.to_date)
              |, as 23h59. Até lá, você pode captar recursos e seguir firme na sua campanha! Após esse prazo, o dinheiro estará na sua conta bancária em até 10 dias úteis.
          .modal-dialog-nav-bottom
            .w-row
              .w-col.w-col-2
              .w-col.w-col-4
                = hidden_field_tag 'anchor', 'announce_expiration'
                = form.button :submit, 'Sim', class:'btn btn-large', id: 'budget-save'
              .w-col.w-col-4
                a#cancel.btn.btn-large.btn-terciary data-ix="modal-dialog-close" href="#announce_expiration"  Não
              .w-col.w-col-2

app/views/catarse_bootstrap/projects/_dashboard_budget.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-10.w-col-push-1
          .w-form
            = @project.display_errors(:budget)
            = form.input :budget, as: :text,
              wrapper: :two_columns,
              wrapper_class: 'w-row u-marginbottom-30 card card-terciary padding-redactor-description',
              input_html: { class: 'redactor positive', required: false },
              validation_text: false
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-4.w-col-push-4
          = hidden_field_tag 'anchor', 'budget'
          = form.button :submit, t('.submit'), class:'btn btn-large', id: 'budget-save'

app/views/catarse_bootstrap/projects/_dashboard_card.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-8
          .w-form
              = @project.display_errors(:card)
              = form.input :uploaded_image, as: :file,
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-6' },
                input_html: { required: false },
                validation_text: false

              = form.input :headline, as: :text,
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7' },
                input_html: { class: 'positive', rows: 3, required: false, maxlength: Project::HEADLINE_MAXLENGTH },
                validation_text: false
        .w-col.w-col-4
          = render 'card'
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-4.w-col-push-4
          = hidden_field_tag 'anchor', 'card'
          = form.hidden_field :project_id, value: @project.id
          = form.button :submit, t('.submit'), class:'btn btn-large', id: 'budget-save'

app/views/catarse_bootstrap/projects/_dashboard_description.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-10.w-col-push-1
          .w-form
              = @project.display_errors(:description)
              =  hidden_field_tag 'project_id', @project.id
              =  hidden_field_tag 'anchor', 'description'

              = form.input :about_html, as: :text, 
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary padding-redactor-description',
                input_html: { class: 'redactor positive', required: true },
                validation_text: false

    .section
      .w-container
        .w-row
          .w-col.w-col-4.w-col-push-4
            = hidden_field_tag 'anchor', 'description'
            = form.button :submit, t('.submit'), class:'btn btn-large', id: 'description-save'

app/views/catarse_bootstrap/projects/_dashboard_nav.html.slim
- edit = defined?(edit_page) || false
= content_for :body_class, 'body-project open'
#project-nav
  .project-nav-wrapper
    nav.w-section.dashboard-nav.side
      = link_to (@project.published? ? project_by_slug_path(@project.permalink) : '#preview'), id: 'dashboard_preview_link', class: 'w-inline-block dashboard-project-name' , data: {target: '#dashboard_preview', tab_group: 'edit'} do
        - if @project.uploaded_image.present?
          img.thumb-project-dashboard src="#{@project.display_image(:project_thumb_large)}" width="114"
        - else
          img.thumb-project-dashboard src="#{image_path('thumb-project.png')}" width="114"
        .fontcolor-negative.lineheight-tight.fontsize-small= @project.name
        = image_tag("catarse_bootstrap/badge-#{@project.mode}-h.png", class: 'u-margintop-10', width: 80)
        - if current_user && current_user.admin?
          .u-marginbottom-10= link_to 'Passar para flex', push_to_flex_project_path(@project), method: 'put'

      #info-links
        = link_to insights_project_path(@project), class: 'dashboard-nav-link-left ' , id: 'dashboard_home_link', data: {tab_group: 'edit'} do
          span.fa.fa-bar-chart.fa-lg.fa-fw
          = t('.start_tab')
        - if @project.published?
          = link_to (edit ? '#reports' : edit_project_path(@project, anchor: 'reports')), id: 'dashboard_reports_link', class: 'dashboard-nav-link-left ' , data: {target: '#dashboard_reports', tab_group: 'edit'} do
            span.fa.fa.fa-table.fa-lg.fa-fw
            = t('.reports_tab')
          = link_to (edit ? '#posts' : edit_project_path(@project, anchor: 'posts')), id: 'dashboard_posts_link', class: 'dashboard-nav-link-left u-marginbottom-30' , data: {target: '#dashboard_posts', tab_group: 'edit'} do
            span.fa.fa-bullhorn.fa-fw.fa-lg
            = t('.posts_tab')
            | &nbsp
            span.badge= @project.posts.count

      .edit-project-div
        - if @project.published? && !@project.is_flexible?
          button#toggle-edit-menu.dashboard-nav-link-left
            span.fa.fa-pencil.fa-fw.fa-lg
            = t('.edit_project')
          #edit-menu-items.w-hidden
            = render partial: 'dashboard_nav_links', locals: {edit: edit}
        - else
          = render partial: 'dashboard_nav_links', locals: {edit: edit}

          .btn-send-draft-fixed
            = render "#{@project.mode}_nav_actions"
  a.btn-dashboard href="#"
    span.fa.fa-bars.fa-lg

app/views/catarse_bootstrap/projects/_flex_preview_explanation.html.slim
- link_to_project = link_to(project_by_slug_url(@project.permalink, locale: ''), project_by_slug_url(@project.permalink, locale: ''))
.u-text-center
  .w-container
    .w-row
      .w-col.w-col-8.w-col-push-2
        .fontweight-semibold.fontsize-large.u-margintop-40= t('projects.dashboard_preview.flex.header_subtitle') 
        p.fontsize-base= t('projects.dashboard_preview.flex.header_text', link: link_to_project).html_safe 
        .w-row.u-marginbottom-30
          .w-col.w-col-3
          .w-col.w-col-6
            = link_to t('projects.dashboard_preview.flex.publish_btn_html'), publish_flexible_project_path(@project.flexible_project), class: 'w-button btn btn-large'
          .w-col.w-col-3
          .w-col.w-col-2

app/views/catarse_bootstrap/projects/_link_fields.html.slim
#links.w-row
    - if f.object.persisted?
      .link
        .w-col.w-col-10.w-col-small-10.w-col-tiny-10
          = f.input_field :link, as: :string, class: 'w-input text-field'
        .w-col.w-col-2.w-col-small-2.w-col-tiny-2
          = link_to_remove_association "", f, class: 'btn btn-small btn-terciary fa fa-lg fa-trash btn-no-border', wrapper_class: 'link' 
    - else
      .link
        .w-col.w-col-10.w-col-small-10.w-col-tiny-10
          = f.input_field :link, as: :string, class: 'w-input text-field positive'
        .w-col.w-col-2.w-col-small-2.w-col-tiny-2
          = link_to_remove_association "", f, class: 'btn btn-small btn-terciary fa fa-lg fa-trash btn-no-border', wrapper_class: 'link' 